services:
  source-database:
    image: postgres:16.3-alpine3.20
    container_name: source-database
    environment:
      POSTGRES_DB: sourcedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data_source:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    networks:
      - etl-network
    
  target-database:
    image: postgres:16.3-alpine3.20
    container_name: target-database
    environment:
      POSTGRES_DB: targetdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data_target:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - etl-network
  
  pgadmin:
    container_name: etl-pgadmin
    image: dpage/pgadmin4:8.9
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8081:80'
    networks:
      - etl-network

networks:
  etl-network:
    driver: bridge

volumes:
  postgres_data_source:
    driver: local
  postgres_data_target:
    driver: local